In [38]:
import numpy as np

In [39]:
# create a 1D array
x = np.array([0, 1, 2, 3, 4, 5, 6])

In [40]:
# find all non-zero elements in x
np.nonzero(x)

(array([1, 2, 3, 4, 5, 6], dtype=int32),)

In [41]:
# create a 5x5 matrix A with random numbers
A = np.random.randn(5, 5)

# create a 5x5 identity matrix B
B = np.eye(5)

In [42]:
A

array([[ 0.49392803, -2.49728553,  1.1347429 ,  0.83272268,  0.93147073],
       [ 0.00256032, -0.08641252, -0.01344065, -1.536838  , -0.87325114],
       [ 0.33076533, -0.2105147 , -0.79851281,  0.07347711, -0.97319849],
       [ 0.12331407,  0.74497355,  0.10706605,  1.0438312 ,  1.81444876],
       [ 0.561243  ,  1.70711453, -0.01602275, -0.31684881, -0.64696873]])

In [43]:
B

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
# calculate the following equations
# A + B
A+B

array([[ 1.49392803, -2.49728553,  1.1347429 ,  0.83272268,  0.93147073],
       [ 0.00256032,  0.91358748, -0.01344065, -1.536838  , -0.87325114],
       [ 0.33076533, -0.2105147 ,  0.20148719,  0.07347711, -0.97319849],
       [ 0.12331407,  0.74497355,  0.10706605,  2.0438312 ,  1.81444876],
       [ 0.561243  ,  1.70711453, -0.01602275, -0.31684881,  0.35303127]])

In [45]:
# A - B
A-B

array([[-0.50607197, -2.49728553,  1.1347429 ,  0.83272268,  0.93147073],
       [ 0.00256032, -1.08641252, -0.01344065, -1.536838  , -0.87325114],
       [ 0.33076533, -0.2105147 , -1.79851281,  0.07347711, -0.97319849],
       [ 0.12331407,  0.74497355,  0.10706605,  0.0438312 ,  1.81444876],
       [ 0.561243  ,  1.70711453, -0.01602275, -0.31684881, -1.64696873]])

In [46]:
# A * B (matrix product)
A*B

array([[ 0.49392803, -0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.08641252, -0.        , -0.        , -0.        ],
       [ 0.        , -0.        , -0.79851281,  0.        , -0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.0438312 ,  0.        ],
       [ 0.        ,  0.        , -0.        , -0.        , -0.64696873]])

In [47]:
# A' (transpose of A)
A.T

array([[ 0.49392803,  0.00256032,  0.33076533,  0.12331407,  0.561243  ],
       [-2.49728553, -0.08641252, -0.2105147 ,  0.74497355,  1.70711453],
       [ 1.1347429 , -0.01344065, -0.79851281,  0.10706605, -0.01602275],
       [ 0.83272268, -1.536838  ,  0.07347711,  1.0438312 , -0.31684881],
       [ 0.93147073, -0.87325114, -0.97319849,  1.81444876, -0.64696873]])

In [48]:
# calculate the mean, sum, max, min value for each column in A
#mean
np.mean(A, axis=1)

array([ 0.17911576, -0.5014764 , -0.31559671,  0.76672673,  0.25770345])

In [49]:
#sum
np.sum(A, axis=1)

array([ 0.8955788 , -2.50738199, -1.57798356,  3.83363364,  1.28851724])

In [50]:
#max
np.max(A, axis=1)

array([1.1347429 , 0.00256032, 0.33076533, 1.81444876, 1.70711453])

In [51]:
#min
np.min(A, axis=1)

array([-2.49728553, -1.536838  , -0.97319849,  0.10706605, -0.64696873])

In [52]:
# normalize A with its max value A_max and min value A_min
# i.e., for any value x in A,
# x = (x - A_min) / (A_max - A_min)
A_max, A_min = A.max(), A.min()
A = (A - A_min)/(A_max - A_min)

In [53]:
A

array([[0.69373791, 0.        , 0.84235906, 0.77231294, 0.79521511],
       [0.57977734, 0.5591423 , 0.57606631, 0.22275202, 0.37665456],
       [0.65589637, 0.53035987, 0.39398827, 0.59622474, 0.35347425],
       [0.60778319, 0.75196171, 0.60401486, 0.82127434, 1.        ],
       [0.70934995, 0.97510648, 0.57546746, 0.5056983 , 0.42913516]])

In [54]:
# advanced exercise
# solve the system of equations:
# 3 * x0 + x1 = 9
# x0 + 2 * x1 = 8

# Ax = b 
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
x

array([2., 3.])

In [55]:
A

array([[3, 1],
       [1, 2]])

In [56]:
b

array([9, 8])

In [57]:
# compare x with the product of inverse A and b


y=np.linalg.inv(A)*b


In [58]:
y

array([[ 3.6, -1.6],
       [-1.8,  4.8]])

In [59]:
comparison = x == y
comparison.all() 

False